#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Open-source resource provided by Papercup Technologies Limited
# Author: Marlene Staib
# IPA-TO-PHONOLOGICAL FEATURES MAPPING DICTIONARY

# Stress markings need to be parsed from the specific dictionary resource used

ipa_to_phonemefeats = {
    '</s>': {'symbol_type': '</s>'},
    '</q>': {'symbol_type': '</q>'},
    '<sil>': {'symbol_type': '<sil>'},
    '<w>': {'symbol_type': '<w>'},
    '<s>': {'symbol_type': '<s>'},
    'a': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'open',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'}, 
    'b': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'bilabial',
          'consonant_manner': 'stop'},
    'd': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'stop'},
    'e': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'close-mid',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'f': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'labiodental',
          'consonant_manner': 'fricative'},
    'h': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'glottal',
          'consonant_manner': 'fricative'},
    'i': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'close',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'j': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'palatal',
          'consonant_manner': 'approximant'},
    'k': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'velar',
          'consonant_manner': 'stop'},
    'kʰ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'velar',
          'consonant_manner': 'stop',
          'diacritic': 'epiglottal'},
    'l': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'lateral-approximant'},
    'l̩': {'symbol_type': 'phoneme',
           'vowel_consonant': 'consonant',
           'VUV': 'voiced',
           'consonant_place': 'alveolar',
           'consonant_manner': 'lateral-approximant',
           'diacritic': 'syllabic'},
    'm': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'bilabial',
          'consonant_manner': 'nasal'},
    'm̩': {'symbol_type': 'phoneme',
           'vowel_consonant': 'consonant',
           'VUV': 'voiced',
           'consonant_place': 'bilabial',
           'consonant_manner': 'nasal',
           'diacritic': 'syllabic'},
    'n': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'nasal'},
    'n̩': {'symbol_type': 'phoneme',
           'vowel_consonant': 'consonant',
           'VUV': 'voiced',
           'consonant_place': 'alveolar',
           'consonant_manner': 'nasal',
           'diacritic': 'syllabic'},
    'o': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'back',
          'vowel_openness': 'close-mid',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'p': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'bilabial',
          'consonant_manner': 'stop'},
    'pʰ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'bilabial',
          'consonant_manner': 'stop',
          'diacritic': 'epiglottal'},
    'pf': {'symbol_type': 'phoneme',
           'vowel_consonant': 'consonant',
           'VUV': 'unvoiced',
           'consonant_place': 'bilabial',
           'consonant_manner': 'affricate'},
    's': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'fricative'},
    't': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'stop'},
    'tʰ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'stop',
          'diacritic': 'epiglottal'},
    'ts': {'symbol_type': 'phoneme',
           'vowel_consonant': 'consonant',
           'VUV': 'unvoiced',
           'consonant_place': 'alveolar',
           'consonant_manner': 'affricate'},
    't͡ʃ': {'symbol_type': 'phoneme',
            'vowel_consonant': 'consonant',
            'VUV': 'unvoiced',
            'consonant_place': 'postalveolar',
            'consonant_manner': 'affricate'},
    'u': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'back',
          'vowel_openness': 'close',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'v': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'labiodental',
          'consonant_manner': 'fricative'},
    'x': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'velar',
          'consonant_manner': 'fricative'},
    'y': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'close',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'z': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'alveolar',
          'consonant_manner': 'fricative'},
    'ç': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'palatal',
          'consonant_manner': 'fricative'},
    'ø': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'close-mid',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'ŋ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'velar',
          'consonant_manner': 'nasal'},
    'œ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'open-mid',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'ɐ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'central',
          'vowel_openness': 'open',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ɔ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'back',
          'vowel_openness': 'open-mid',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'ə': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'central',
          'vowel_openness': 'mid',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ɛ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front',
          'vowel_openness': 'open-mid',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ɪ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front_central',
          'vowel_openness': 'close_close-mid',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ʃ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'postalveolar',
          'consonant_manner': 'fricative'},
    'ʊ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'central_back',
          'vowel_openness': 'close_close-mid',
          'vowel_roundedness': 'unrounded',
          'stress': 'unstressed'},
    'ʏ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'vowel',
          'VUV': 'voiced',
          'vowel_frontness': 'front_central',
          'vowel_openness': 'close_close-mid',
          'vowel_roundedness': 'rounded',
          'stress': 'unstressed'},
    'ɡ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'velar',
          'consonant_manner': 'stop'},
    'ɟ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'palatal',
          'consonant_manner': 'stop'},
    'ɲ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'palatal',
          'consonant_manner': 'nasal'},
    'ʁ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'uvular',
          'consonant_manner': 'fricative'},
    'c': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'palatal',
          'consonant_manner': 'stop'},
    'cʰ': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'unvoiced',
          'consonant_place': 'palatal',
          'consonant_manner': 'stop',
          'diacritic': 'epiglottal'},
    'w': {'symbol_type': 'phoneme',
          'vowel_consonant': 'consonant',
          'VUV': 'voiced',
          'consonant_place': 'labial-velar',
          'consonant_manner': 'approximant'},
}
